name: carp_background_location_example
description: A example app for the CARP Background Location plugin.
publish_to: 'none'
version: 4.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carp_background_location:
    path: ../
  permission_handler: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
